name: Deploy Backend to Lambda

on:
  push:
    branches:
      - main # Deploy only when main branch changes (you can change to 'backend' branch if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Zip Lambda function
        run: |
          cd backend
          zip -r ../function.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name anti-flex-backend \
            --zip-file fileb://function.zip
